import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>

      <main className={styles.main}>
      <a href=''>
        <img />
        <h1>Events in London</h1>
        <p>
        {' '}
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus, atque. Voluptates, dolor saepe veritatis quia ipsam velit natus aspernatur id molestiae quae deserunt error repellat, impedit iusto ad? Aliquid praesentium, repudiandae nihil optio accusantium recusandae tempora corrupti omnis rerum! Earum optio unde, sapiente cumque repellendus saepe ipsum consequatur consectetur quaerat laborum debitis quisquam repudiandae asperiores dolore aperiam incidunt odit, placeat ratione aspernatur laudantium eius.
        </p>
      </a>
      <a href=''>
        <img />
        <h1>Events in San Francisco</h1>
        <p>
        {' '}
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus, atque. Voluptates, dolor saepe veritatis quia ipsam velit natus aspernatur id molestiae quae deserunt error repellat, impedit iusto ad? Aliquid praesentium, repudiandae nihil optio accusantium recusandae tempora corrupti omnis rerum! Earum optio unde, sapiente cumque repellendus saepe ipsum consequatur consectetur quaerat laborum debitis quisquam repudiandae asperiores dolore aperiam incidunt odit, placeat ratione aspernatur laudantium eius.
        </p>
      </a>
      <a href=''>
        <img />
        <h1>Events in Barcelona</h1>
        <p>
        {' '}
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus, atque. Voluptates, dolor saepe veritatis quia ipsam velit natus aspernatur id molestiae quae deserunt error repellat, impedit iusto ad? Aliquid praesentium, repudiandae nihil optio accusantium recusandae tempora corrupti omnis rerum! Earum optio unde, sapiente cumque repellendus saepe ipsum consequatur consectetur quaerat laborum debitis quisquam repudiandae asperiores dolore aperiam incidunt odit, placeat ratione aspernatur laudantium eius.
        </p>
      </a>
      </main>

      <footer className={styles.footer}>
        <p> © Creeated by Varun Chaubey</p>
      </footer>
    </div>
  )
}
